POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "firstName": "Manas",
  "lastName": "Agrawal",
  "email": "asd@s.com",
  "password": "12345678"
}




###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "asd@s.com",
  "password": "12345678"
}

###
GET http://localhost:8080/api/login/me

###
POST http://localhost:8080/api/login/logout

###
GET http://localhost:8080/api/marketData/currentStockPrice?symbol=NVDA

###
GET http://localhost:8080/api/marketData/StockPriceHistory?
    symbol=NVDA&startDate=2025-11-10&endDate=2025-11-17

###
POST http://localhost:8080/api/portfolio
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 5
}
###
POST http://localhost:8080/api/portfolio/buy
Content-Type: application/json

{
  "symbol": "NVDA",
  "quantity": 5
}

###
POST http://localhost:8080/api/portfolio/sell
Content-Type: application/json

{
  "symbol": "NVDA",
  "quantity": 10
}


###
GET http://localhost:8080/api/marketData/stockData?symbol=MSFT


###
GET http://localhost:8080/api/portfolio/watchList

###
POST http://localhost:8080/api/portfolio/watchlist?
    symbol=RIOT

###
DELETE http://localhost:8080/api/portfolio/watchlist?
    symbol=AAPL

